/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "BuildZeroBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "BuildZeroCognitoUserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "BuildZeroDatabase": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "BuildZeroImageBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "BuildZeroPoolWebClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
    "BuildZeroRedisCache": {
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Redis"
      "username": string
    }
    "BuildZeroVpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "BuildZeroWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "PostgresMigrator": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
