/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "BuildZeroAuthn": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "BuildZeroBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "BuildZeroDb": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "BuildZeroImageBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "BuildZeroPoolWebClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
    "BuildZeroRedisCache": {
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Redis"
      "username": string
    }
    "BuildZeroVpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "BuildZeroWebApp": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "CloudfrontDistributionId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ContentfulAccessToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ContentfulSpaceId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PostHogKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PostgresMigrator": {
      "name": string
      "type": "sst.aws.Function"
    }
    "RevalidateSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}